clean:
	./gradlew clean
build:
	./gradlew clean build
run:
	./gradlew run
install:
	./gradlew clean install
run-dist:
	./build/install/app/bin/app
lint:
	./gradlew checkstyleMain checkstyleTest
test:
	./gradlew test
report:
	./gradlew jacocoTestReport
update-deps:
	./gradlew useLatestVersions